#!/usr/bin/env python3
"""Convert an image into a 64x128 1-bit OLED bitmap for THEME_ART.

The Sofle Choc Pro OLED runs in OLED_ROTATION_270, so the logical drawing
canvas is 64 px wide x 128 px tall (portrait). Raw bitmaps are stored
page-major: 16 pages of 64 columns, each byte holding 8 vertical pixels
(bit 0 = topmost pixel of that page). This matches oled_write_raw_P().

Usage:
    python3 convert_image.py my_picture.png > art.h
    # then in keymap.c, near the other includes, add:  #include "art.h"

Requires Pillow:  pip install Pillow
"""
import sys
from PIL import Image, ImageOps

WIDTH, HEIGHT = 64, 128
THRESHOLD = 128  # pixels brighter than this become "on"


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: convert_image.py <image> [--invert] [--fit] > art.h")

    invert = "--invert" in sys.argv
    fit = "--fit" in sys.argv      # letterbox instead of crop-to-fill
    dither = "--dither" in sys.argv  # Floyd-Steinberg (best for photos)

    img = Image.open(sys.argv[1]).convert("L")
    img = ImageOps.autocontrast(img)
    if fit:
        img = ImageOps.pad(img, (WIDTH, HEIGHT), color=0)
    else:
        img = ImageOps.fit(img, (WIDTH, HEIGHT))
    if dither:
        img = img.convert("1")  # 1-bit with Floyd-Steinberg dithering
    else:
        img = img.point(lambda p: 255 if p >= THRESHOLD else 0)
    img = img.convert("L")
    px = img.load()

    data = []
    for page in range(HEIGHT // 8):       # 16 pages
        for col in range(WIDTH):          # 64 columns
            byte = 0
            for bit in range(8):
                y = page * 8 + bit
                on = px[col, y] > 0
                if invert:
                    on = not on
                if on:
                    byte |= (1 << bit)
            data.append(byte)

    print("#pragma once")
    print("// generated by convert_image.py from", sys.argv[1])
    print("#define HAVE_ART_BITMAP")
    print(f"static const char ART_BITMAP [] PROGMEM = {{")
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        print(f"    {row},")
    print("};")


if __name__ == "__main__":
    main()
